server:
  port: 8093
spring:
  application:
    name: gateway-global-filter
  cloud:
    nacos:
      discovery:
        server-addr: 47.94.229.125:8848
#    gateway:
#      routes:
#        - id: filter_route
#          uri: http://47.94.229.125:8848
#          predicates:
#            - Path=/nacos
#          filters:
#            - RequestTimeFilter

logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug

