server:
  port: 8091
spring:
  application:
    name: gateway-route
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        # 通过IP 地址转发
        - id: path_route
          uri: http://localhost:8090
          predicates:
            - Path=/route
        #  通过服务地址
#        - id: path_route_lb
#          uri: lb://gateway-server
#          predicates:
#            - Path=/route/**
        # Before 路由断言
#        - id: path_route_before
#          uri: http://blog.lixc.top/
#          predicates:
#            - Before=2020-05-10T14:45:39.145+08:00[Asia/Shanghai]
        # After 路由断言
#        - id: path_route_after
#          uri: http://blog.lixc.top/
#          predicates:
#            - After=2020-05-01T14:45:39.145+08:00[Asia/Shanghai]
