server:
  port: 8083
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: ribbon-rest
# 针对 ribbon-server ribbon配置
ribbon-server:
  ribbon:
    # 加载规则
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
# 饥饿加载
ribbon:
  eager-load:
    enabled: true
    # 加载列表 多个 使用逗号隔开
    clients: ribbon-server