server:
  port: 8092
spring:
  application:
    name: gateway-route
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: add_request_header_route
          uri: https://example.org
          predicates:
            - After=2020-05-01T14:45:39.145+08:00[Asia/Shanghai]
          filters:
            # 请求添加名为 X-Request-Foo ，值为 Bar 的请求头
          #  - AddRequestHeader=X-Request-Foo, Bar
          #   请求参数 token:abc
            - AddRequestParameter=token,abc
          # 响应头请求参数
            - AddResponseHeader=token,abc123
             # 过滤器工厂名称
            - name: Retry
              args:
                  # 默认 3
                retries: 3
                series: SERVER_ERROR
                statuses: INTERNAL_SERVER_ERROR,BAD_GATEWAY
                methods: GET,POST,DELETE,PUT
                exceptions:
                  - java.io.IOException
                  - java.util.concurrent.TimeoutException



logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug
